var manchesterUnited = "http://www.footballpictures.net/data/media/132/manchester_united_logo_2.jpg";
var chelsea = "http://fullhdpictures.com/wp-content/uploads/2015/10/Chelsea-Logos.jpg";

var ManchesterUnited = [
    {
      "HA": "A",
      "Pos": "Goalkeeper",
      "Jrsy": 1,
      "PID": 51940,
      "Name": "David de Gea",
      "DOB": "1990-11-07T00:00:00",
      "Ht": 192,
      "Wt": 76,
      "Cntry": "Spain",
      "PosReal": "Goalkeeper",
      "PosSide": "",
      "Birthplace": "Madrid",
      "Nationality": "Spain",
      "Foot": "R",
	  "Team" : manchesterUnited
    },
    {
      "HA": "A",
      "Pos": "Defender",
      "Jrsy": 36,
      "PID": 40002,
      "Name": "Matteo Darmian",
      "DOB": "1989-12-02T00:00:00",
      "Ht": 182,
      "Wt": 70,
      "Cntry": "Italy",
      "PosReal": "Full Back",
      "PosSide": "Left/Right",
      "Birthplace": "Legnano",
      "Nationality": "Italy",
      "Foot": "L",
	  "Team" : manchesterUnited
    },
    {
      "HA": "A",
      "Pos": "Defender",
      "Jrsy": 12,
      "PID": 55909,
      "Name": "Chris Smalling",
      "DOB": "1989-11-22T00:00:00",
      "Ht": 194,
      "Wt": 90,
      "Cntry": "England",
      "PosReal": "Central Defender",
      "PosSide": "Centre",
      "Birthplace": "Greenwich",
      "Nationality": "England",
      "Foot": " ",
	  "Team" : manchesterUnited
    },
    {
      "HA": "A",
      "Pos": "Defender",
      "Jrsy": 5,
      "PID": 58893,
      "Name": "Marcos Rojo",
      "DOB": "1990-03-20T00:00:00",
      "Ht": 187,
      "Wt": 80,
      "Cntry": "Argentina",
      "PosReal": "Central Defender",
      "PosSide": "Left/Centre",
      "Birthplace": "La Plata",
      "Nationality": "Argentina",
      "Foot": "L",
	  "Team" : manchesterUnited
    },
    {
      "HA": "A",
      "Pos": "Defender",
      "Jrsy": 4,
      "PID": 76359,
      "Name": "Phil Jones",
      "DOB": "1992-02-21T00:00:00",
      "Ht": 185,
      "Wt": 72,
      "Cntry": "England",
      "PosReal": "Central Defender",
      "PosSide": "Centre",
      "Birthplace": "Preston",
      "Nationality": "England",
      "Foot": "R",
	  "Team" : manchesterUnited
    },
    {
      "HA": "A",
      "Pos": "Midfielder",
      "Jrsy": 31,
      "PID": 15208,
      "Name": "Bastian Schweinsteiger",
      "DOB": "1984-08-01T00:00:00",
      "Ht": 183,
      "Wt": 79,
      "Cntry": "Germany",
      "PosReal": "Central Midfielder",
      "PosSide": "Centre",
      "Birthplace": "Kolbermoor",
      "Nationality": "Germany",
      "Foot": "R",
	  "Team" : manchesterUnited
    },
    {
      "HA": "A",
      "Pos": "Midfielder",
      "Jrsy": 28,
      "PID": 42774,
      "Name": "Morgan Schneiderlin",
      "DOB": "1989-11-08T00:00:00",
      "Ht": 181,
      "Wt": 75,
      "Cntry": "France",
      "PosReal": "Defensive Midfielder",
      "PosSide": "Centre",
      "Birthplace": "Obernai",
      "Nationality": "France",
      "Foot": " ",
	  "Team" : manchesterUnited
    },
    {
      "HA": "A",
      "Pos": "Midfielder",
      "Jrsy": 8,
      "PID": 43670,
      "Name": "Juan Mata",
      "DOB": "1988-04-28T00:00:00",
      "Ht": 170,
      "Wt": 63,
      "Cntry": "Spain",
      "PosReal": "Attacking Midfielder",
      "PosSide": "Left/Centre/Right",
      "Birthplace": "Burgos",
      "Nationality": "Spain",
      "Foot": "L",
	  "Team" : manchesterUnited
    },
    {
      "HA": "A",
      "Pos": "Midfielder",
      "Jrsy": 21,
      "PID": 59846,
      "Name": "Ander Herrera",
      "DOB": "1989-08-14T00:00:00",
      "Ht": 182,
      "Wt": 70,
      "Cntry": "Spain",
      "PosReal": "Attacking Midfielder",
      "PosSide": "Left/Centre/Right",
      "Birthplace": "Bilbao",
      "Nationality": "Spain",
      "Foot": "B",
	  "Team" : manchesterUnited
    },
    {
      "HA": "A",
      "Pos": "Midfielder",
      "Jrsy": 9,
      "PID": 148225,
      "Name": "Anthony Martial",
      "DOB": "1995-12-05T00:00:00",
      "Ht": 181,
      "Wt": 76,
      "Cntry": "France",
      "PosReal": "Striker",
      "PosSide": "Left/Centre/Right",
      "Birthplace": "",
      "Nationality": "",
      "Foot": " ",
	  "Team" : manchesterUnited
    },
    {
      "HA": "A",
      "Pos": "Striker",
      "Jrsy": 10,
      "PID": 13017,
      "Name": "Wayne Rooney",
      "DOB": "1985-10-24T00:00:00",
      "Ht": 178,
      "Wt": 78,
      "Cntry": "England",
      "PosReal": "Second Striker",
      "PosSide": "Left/Centre/Right",
      "Birthplace": "Liverpool",
      "Nationality": "England",
      "Foot": " ",
	  "Team" : manchesterUnited
    },
    {
      "HA": "A",
      "Pos": "Substitute",
      "Jrsy": 16,
      "PID": 2404,
      "Name": "Michael Carrick",
      "DOB": "1981-07-28T00:00:00",
      "Ht": 188,
      "Wt": 74,
      "Cntry": "England",
      "PosReal": "Central Midfielder",
      "PosSide": "Centre",
      "Birthplace": "Wallsend",
      "Nationality": "England",
      "Foot": " ",
	  "Team" : manchesterUnited
    },
    {
      "HA": "A",
      "Pos": "Substitute",
      "Jrsy": 27,
      "PID": 41184,
      "Name": "Marouane Fellaini",
      "DOB": "1987-11-22T00:00:00",
      "Ht": 194,
      "Wt": 85,
      "Cntry": "Belgium",
      "PosReal": "Attacking Midfielder",
      "PosSide": "Centre",
      "Birthplace": "Brussels",
      "Nationality": "Belgium",
      "Foot": " ",
	  "Team" : manchesterUnited
    },
    {
      "HA": "A",
      "Pos": "Substitute",
      "Jrsy": 17,
      "PID": 58877,
      "Name": "Daley Blind",
      "DOB": "1990-03-09T00:00:00",
      "Ht": 180,
      "Wt": 72,
      "Cntry": "Netherlands",
      "PosReal": "Defensive Midfielder",
      "PosSide": "Centre",
      "Birthplace": "Amsterdam",
      "Nationality": "Netherlands",
      "Foot": "B",
	  "Team" : manchesterUnited
    },
    {
      "HA": "A",
      "Pos": "Substitute",
      "Jrsy": 50,
      "PID": 101982,
      "Name": "Sam Johnstone",
      "DOB": "1993-03-25T00:00:00",
      "Ht": 193,
      "Wt": 85,
      "Cntry": "England",
      "PosReal": "Goalkeeper",
      "PosSide": "",
      "Birthplace": "",
      "Nationality": "",
      "Foot": " ",
	  "Team" : manchesterUnited
    },
    {
      "HA": "A",
      "Pos": "Substitute",
      "Jrsy": 7,
      "PID": 106824,
      "Name": "Memphis Depay",
      "DOB": "1994-02-13T00:00:00",
      "Ht": 176,
      "Wt": 78,
      "Cntry": "Netherlands",
      "PosReal": "Second Striker",
      "PosSide": "Left/Right",
      "Birthplace": "Moordrecht",
      "Nationality": "Netherlands",
      "Foot": " ",
	  "Team" : manchesterUnited
    },
    {
      "HA": "A",
      "Pos": "Substitute",
      "Jrsy": 35,
      "PID": 109322,
      "Name": "Jesse Lingard",
      "DOB": "1992-12-15T00:00:00",
      "Ht": 168,
      "Wt": 58,
      "Cntry": "England",
      "PosReal": "Attacking Midfielder",
      "PosSide": "Left/Right",
      "Birthplace": "",
      "Nationality": "",
      "Foot": " ",
	  "Team" : manchesterUnited
    },
    {
      "HA": "A",
      "Pos": "Substitute",
      "Jrsy": 44,
      "PID": 156689,
      "Name": "Andreas Pereira",
      "DOB": "1996-01-01T00:00:00",
      "Ht": 177,
      "Wt": 66,
      "Cntry": "Brazil",
      "PosReal": "Attacking Midfielder",
      "PosSide": "Left/Centre/Right",
      "Birthplace": "",
      "Nationality": "Belgium",
      "Foot": " ",
	  "Team" : manchesterUnited
    },
  ];


// ----------------------------------------------------------- //

$(document).on("pagecreate","#manchesterUnited", onPageCreated);
function onPageCreated() {

	var feedUrl = "http://api.football-data.org/v1/teams/66/players";

	var xmlhttp=new XMLHttpRequest();
	xmlhttp.open("GET", feedUrl, false);
	xmlhttp.send();
		
	var teamsObject= JSON.parse(xmlhttp.responseText);

	var myTeam = teamsObject.players;

	ractive = new Ractive({
	el: '#listManu',
	
	template: '#template',
	
	data: {listManu: myTeam}
});
}